#!/usr/bin/env bash
# =============================================================================
# gen-stream-ports.sh
# =============================================================================
# Generates /etc/nginx/stream.d/gameserver-ports.conf
# Each game-server pod listens on a port in [PORT_MIN, PORT_MAX] via
# hostNetwork. This script creates one Nginx stream server block per port
# so that TLS is terminated and traffic is forwarded to 127.0.0.1:<port>.
#
# Run on the VM (requires root / sudo):
#   sudo bash scripts/gen-stream-ports.sh
#   sudo nginx -t && sudo systemctl reload nginx
# =============================================================================

set -euo pipefail

PORT_MIN="${PORT_MIN:-30000}"
PORT_MAX="${PORT_MAX:-31000}"
OUT="/etc/nginx/stream.d/gameserver-ports.conf"

echo "Generating stream blocks for ports ${PORT_MIN}–${PORT_MAX} → ${OUT}"

{
  echo "# AUTO-GENERATED by gen-stream-ports.sh – do not edit manually"
  echo "# Re-run the script to regenerate after changing PORT_MIN / PORT_MAX"
  echo ""
  for port in $(seq "$PORT_MIN" "$PORT_MAX"); do
    echo "server {"
    echo "    listen ${port} ssl;"
    echo "    proxy_pass 127.0.0.1:${port};"
    echo "}"
    echo ""
  done
} | sudo tee "$OUT" > /dev/null

echo "Done. Run: sudo nginx -t && sudo systemctl reload nginx"
